Generating data
htmlacademy-univer-javascript-1/1989431-kekstagram-4 pull request #3
Opened 2023-10-13 17:04 UTC by EgorkaaBadddy

2023-10-15 09:23 UTC, MaksimovG requested changes

2023-10-15 09:23 UTC, MaksimovG commented on js/main.js
> +const DESCRIPTION = [
названа не по критериям

2023-10-15 09:23 UTC, MaksimovG commented on js/main.js
> +const AUTHORNAME = [
названа не по критериям

2023-10-15 09:23 UTC, MaksimovG commented on js/main.js
> +/*Хорошая ли это практика создавать вот так через const????*/
ужасная практика. И очень интересно откуда вы все этот ужас взяли. А так же куча магических чисел (опять же перечитываем критерии)

2023-10-15 09:23 UTC, MaksimovG commented on js/main.js
> +  comments : generateComments(getRandomInt(0,29))
тут тоже куча магических чисел

2023-10-15 09:23 UTC, MaksimovG commented on js/main.js
> +
обилие ненужных пустых строк.

2023-10-15 09:23 UTC, MaksimovG commented on js/main.js
> +Array.from({length : 25}, createObject);
Это должна была быть функция, которая создает и возвращает массив

2023-10-15 09:23 UTC, MaksimovG commented on js/main.js
> +const createObject = () => ({
слишиком абсрактное название

2023-10-17 15:23 UTC, EgorkaaBadddy commented
fix bugs

2023-10-19 09:06 UTC, MaksimovG approved these changes

2023-10-19 09:06 UTC, merged