Module9 task1
htmlacademy-univer-javascript-1/1989431-kekstagram-4 pull request #9
Opened 2023-12-01 16:08 UTC by EgorkaaBadddy

2023-12-04 16:33 UTC, MaksimovG requested changes

2023-12-04 16:33 UTC, MaksimovG commented on js/form-picture-effects.js
> +
лишняя пустая строка

2023-12-04 16:33 UTC, MaksimovG commented on js/form.js
> +const patternWithSpaces = /(?:^|\s)(#[a-zа-яё0-9]{1,19})(?=\s|$)/gi;
константы

2023-12-04 16:33 UTC, MaksimovG commented on js/form.js
> +  document.addEventListener('keydown', handleKeyDown);
работа. с названиями функций и обработчиков

2023-12-04 16:33 UTC, MaksimovG commented on js/form.js
> +  return hashtagsArray.length === new Set(hashtagsArray).size;
array и obiect в названиях быть не должно быть в названияз

2023-12-08 07:18 UTC, MaksimovG requested changes

2023-12-08 07:18 UTC, MaksimovG commented on index.html
> +  <script src="node_modules/pristinejs/dist/pristine.min.js"></script>
перед своими скриптами

2023-12-08 07:18 UTC, MaksimovG commented on js/form.js
> +// import {editEffect} from './form-picture-effects.js';
комментариев быть не должно

2023-12-08 07:18 UTC, MaksimovG commented on js/form.js
> +const MAX_HASHTAG_LENGTH = 5;
константы должны идти перед основным кодом

2023-12-08 07:18 UTC, MaksimovG commented on js/form.js
> +const MAX_HASHTAG_LENGTH = 5;
В общем пора сходить и перечитать критерии. Надоедает уже делать замечания, которых к концу семестра не должно быть

2023-12-08 07:18 UTC, MaksimovG commented on js/form.js
> +};
Вот здесь должна быть логика проверки, что это картинка

2023-12-09 11:30 UTC, MaksimovG requested changes

2023-12-09 11:30 UTC, MaksimovG commented on index.html
> +  <script src="node_modules/pristinejs/dist/pristine.min.js"></script>
Проигнорированный комментарий. Вендорные файлы подключаются до своих

2023-12-09 11:30 UTC, MaksimovG commented on js/form.js
> +
лишняя пустая строка

2023-12-09 11:30 UTC, MaksimovG commented on js/form.js
> +const MULTIPLE_VALID_HASHTAGS = /(?:^|\s)(#[a-zа-яё0-9]{1,19})(?=\s|$)/gi;
конастанты идут перед основным кодом. 
Я буду целенаправлено разворачивать работу пока не увижу что все критерии изучены и выполняются

2023-12-09 11:30 UTC, MaksimovG commented on js/form.js
> +const form = bodyElement.querySelector('.img-upload__form');
здесь по факту тоже есть нарушение критерия связанного с названием таких переменных

2023-12-09 11:30 UTC, MaksimovG commented on js/form.js
> +
где-то между функциями 1 строка, где-то 2

2023-12-11 18:22 UTC, MaksimovG approved these changes

2023-12-11 18:22 UTC, MaksimovG commented on js/form.js
> +const MULTIPLE_VALID_HASHTAGS = /(?:^|\s)(#[a-zа-яё0-9]{1,19})(?=\s|$)/gi;
Константы идут перед основным кодом

2023-12-11 18:22 UTC, merged

2023-12-11 18:31 UTC, EgorkaaBadddy commented on js/form.js
> +const MULTIPLE_VALID_HASHTAGS = /(?:^|\s)(#[a-zа-яё0-9]{1,19})(?=\s|$)/gi;
Добрый вечер, ну они ж ведь вроде идут перед ним....